# _config.yml
title: "Análise de Dados - Serviço Família Acolhedora"
author: "Núcleo de Gestão da Informação e do Conhecimento - SEGES/MGI"
language: "pt"
execute:
  execute_notebooks: "auto"  # Executar notebooks automaticamente
html:
  baseurl: "/familia-acolhedora"
launch_buttons:
  binderhub_url: "https://mybinder.org"  # URL para suporte ao Binder
  thebe: true                            # Habilitar Thebe para interatividade